Adds support for chords in MusicXML importer
CoderLine/alphaTab pull request #1299
Opened 2023-11-21 18:13 UTC by coluzziandrea

### Issues
Fixes #667 

![image](https://github.com/CoderLine/alphaTab/assets/12852000/0cd9d241-8f82-4cb8-8cae-a3477f5b9e84)

### Proposed changes

### Checklist
- [x] I consent that this change becomes part of alphaTab under it's current or any future open source license
- [x] Changes are implemented
- [x] Existing builds tests pass
- [x] New tests were added

## Further details
- [ ] This is a breaking change
- [ ] This change will require update of the documentation/website

2023-11-24 06:46 UTC, coluzziandrea commented
Hi @Danielku15, could you please take a look at this PR? 😊

2023-11-29 13:05 UTC, Danielku15 requested changes
Thanks for preparing this change and sorry for the delay. I currently have not much time to work on alphaTab. 

Can you maybe also take care that the C# variant compiles?

2023-11-30 09:45 UTC, coluzziandrea commented on src/importer/MusicXmlImporter.ts
> +        let rootStep: string | null = null;
you mean for cross-platform compiles?

2023-12-03 10:15 UTC, Danielku15 commented on src/importer/MusicXmlImporter.ts
> +        let rootStep: string | null = null;
On one hand yes. But also just from cleanliness in the code: We want to have an empty string anyhow, relying on the fact that null will become an empty string when concatenated is not so good.

2023-12-09 14:26 UTC, coluzziandrea commented
@Danielku15 I've addressed comments, take a look when you have time please

2023-12-09 16:24 UTC, merged

2023-12-09 16:25 UTC, Danielku15 commented
@coluzziandrea Thanks a lot for your contribution. I took care of the remaining updates and cross compilation bits.

2023-12-13 22:34 UTC, goodgame365 commented
But after the update. the exported GP format file cannot be opened in Guitar Pro 8. When I try to open it, Guitar Pro 8 crashes.